spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/web
    username: "{cipher}9b9260251134ec3b38e0bf9697d8b8e18ab1944346a23abd9d8a7d3fae90f326"
    password: "{cipher}0c889f6a014d1614eccd0b8ccabb4c41fb59fa72bcdb271529d84a21b84cea7e"
mybatis:
  type-aliases-package: com.beyond.university.*.model.vo
  mapper-locations:
    - classpath:mappers/**/*.xml
springdoc:
  swagger-ui:
    operations-sorter: method
  paths-to-match:
    - /api/v1/**
