spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/web
    username: "{cipher}c38e6a95f96acb7f99de21ceefa1f9267165f404562e7ed27cdd49f70d2b6550"
    password: "{cipher}905a2bbac819946d18ec3038ad8929fb978c1563eb5da95785c47199f687b8b2"
  data:
    redis:
      host: localhost
      port: 6379
      password: "{cipher}2f23d18a56edda1ab7f34e633949500ed1760babaaf65757d9f40a36138a4043"
mybatis:
  type-aliases-package: com.beyond.university.*.model.vo
  mapper-locations:
    - classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: NULL
springdoc:
  swagger-ui:
    operations-sorter: method
  paths-to-match:
    - /api/v1/**
jwt:
  issuer: https://accounts.beyond.com
  secret: "{cipher}9aa3bc289e2ef57fa9b4ae86b440811b888f463c1ad3ec0e9bed1de8fe9a5609ef6b5a852f4c5ba2e373fb460046cf199b2f57661df6edd5b5da27e00c5abb4f"
